# Mono Repo/docker-compose.yml
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    # command: "-js"

  bombermanbackend:
    image: bombermanbackend
    build:
      context: .
      dockerfile: Dockerfile # <-- CHANGED: Now directly in context root
    environment:
      - NATS_URL=nats://nats:4222
      # - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - nats
