# Mono Repo/docker-compose.debug.yml
services:
  bombermanbackend:
    image: bombermanbackend-debug
    build:
      context: .
      dockerfile: Dockerfile # <-- CHANGED: Now directly in context root
      args:
        - configuration=Debug
    ports:
      - "5000:5000"
    environment:
      - NATS_URL=nats://nats:4222
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      # Adjust volume paths if needed, they are relative to compose file
      - ./BombermanBackend:/source/BombermanBackend:rw
      - ./BombermanBackend.Contracts:/source/BombermanBackend.Contracts:rw
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - nats
